---
- name: create a windows user
  hosts: win
  gather_facts: false
  tasks: 
    - name: create windows users
      win_user:
        name: linda
        password: "@nsible123"
        state: present
        groups: 
          - Users
